# TerraBungee
# (C) 2020 Saghetti

# Node Config

# The name of this node, used to identify it on the network. Must be unique.
node-name: example-node

# HTTP server information.
http:
  # The host and port that the HTTP server should run on
  host: 0.0.0.0
  port: 8081

# The URL that the controller can be accessed from
# NOTE: must end with a slash
# It is reccomended to use 127.0.0.1 instead of localhost due to reduced latency
controller-url: http://127.0.0.1:8080/

# Limits on how much system resources this node is allowed to use.
resource-limits:
  # Maximum amount of server instances that can be hosted on this node.
  # Make sure that you set this value appropriately, your machine may run out of memory if you create too many instances.
  max-instances: 10

# How TerraBungee should communicate over the network.
communication:
  # The prefix that TerraBungee should use for channels.
  # Allows running multiple networks using a single Redis server.
  # It is reccomended to leave this value blank.
  channel-prefix: ""

# Hostname for this machine (ex: the internal IP).
# Use localhost if you're running all your services on the same machine (Controller, Nodes, and Proxies)
hostname: "127.0.0.1"
